server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: post
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**, 
        - id: product
          uri: http://localhost:8083
          predicates:
            - Path=/products/**, 
        - id: trading
          uri: http://localhost:8084
          predicates:
            - Path=/tradings/**, 
        - id: alarm
          uri: http://localhost:8085
          predicates:
            - Path=/alarms/**, 
        - id: mypage
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: post
          uri: http://post:8080
          predicates:
            - Path=/posts/**, 
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/products/**, 
        - id: trading
          uri: http://trading:8080
          predicates:
            - Path=/tradings/**, 
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path=/alarms/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
