---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: username/post:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: username/product:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  labels:
    app: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
    spec:
      containers:
        - name: trading
          image: username/trading:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm
  labels:
    app: alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm
  template:
    metadata:
      labels:
        app: alarm
    spec:
      containers:
        - name: alarm
          image: username/alarm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypage
  template:
    metadata:
      labels:
        app: mypage
    spec:
      containers:
        - name: mypage
          image: username/mypage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: post
  labels:
    app: post
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: post


---


apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: product


---


apiVersion: v1
kind: Service
metadata:
  name: trading
  labels:
    app: trading
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: trading


---


apiVersion: v1
kind: Service
metadata:
  name: alarm
  labels:
    app: alarm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: alarm


---


apiVersion: v1
kind: Service
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mypage

